// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSINzbJLaYb3NQDR1bXeuJwjoN419wR-M',
    appId: '1:555657826524:web:04a91a45644100bbf52419',
    messagingSenderId: '555657826524',
    projectId: 'bestmlawi-c2b5c',
    authDomain: 'bestmlawi-c2b5c.firebaseapp.com',
    databaseURL: 'https://bestmlawi-c2b5c-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-c2b5c.firebasestorage.app',
    measurementId: 'G-4S9P1XJWVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6sVZeY1VQ7TnHT_lRrHahH7NfKKF0wE',
    appId: '1:555657826524:android:08c5c52a0c41dba4f52419',
    messagingSenderId: '555657826524',
    projectId: 'bestmlawi-c2b5c',
    databaseURL: 'https://bestmlawi-c2b5c-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-c2b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXx8EWylUNkCtFU0cAp4qZI80OQv86CBU',
    appId: '1:555657826524:ios:a196c75d74bd4facf52419',
    messagingSenderId: '555657826524',
    projectId: 'bestmlawi-c2b5c',
    databaseURL: 'https://bestmlawi-c2b5c-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-c2b5c.firebasestorage.app',
    iosBundleId: 'com.example.projetBestMlewi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXx8EWylUNkCtFU0cAp4qZI80OQv86CBU',
    appId: '1:555657826524:ios:a196c75d74bd4facf52419',
    messagingSenderId: '555657826524',
    projectId: 'bestmlawi-c2b5c',
    databaseURL: 'https://bestmlawi-c2b5c-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-c2b5c.firebasestorage.app',
    iosBundleId: 'com.example.projetBestMlewi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSINzbJLaYb3NQDR1bXeuJwjoN419wR-M',
    appId: '1:555657826524:web:e91a50a2d2114c02f52419',
    messagingSenderId: '555657826524',
    projectId: 'bestmlawi-c2b5c',
    authDomain: 'bestmlawi-c2b5c.firebaseapp.com',
    databaseURL: 'https://bestmlawi-c2b5c-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-c2b5c.firebasestorage.app',
    measurementId: 'G-KZ2X3LM43G',
  );
}
